package org.intuit.consumer;

import java.util.concurrent.BlockingQueue;

/**
 * Consumer class removes messages from a shared BlockingQueue and "processes" them.
 * Multiple consumers may run concurrently and safely consume from the same queue.
 * <p>
 * Key behaviors:
 * - Consumes messages generated by producers.
 * - Blocks until messages are available.
 * - Stops gracefully when interrupted.
 */
public class Consumer implements Runnable {

    private final BlockingQueue<String> queue;  // Shared buffer
    private final int consumerId;               // Unique identifier for each consumer

    public Consumer(BlockingQueue<String> queue, int consumerId) {
        this.queue = queue;
        this.consumerId = consumerId;
    }

    @Override
    public void run() {
        try {
            // Continue consuming until thread is interrupted
            while (!Thread.currentThread().isInterrupted()) {

                // Blocks if queue is empty
                String message = queue.take();

                System.out.println("    [CONSUMED by C" + consumerId + "] -> " + message);

                Thread.sleep(600);
            }

        } catch (InterruptedException e) {
            System.out.println("Consumer " + consumerId + " interrupted.");
            Thread.currentThread().interrupt();
        }
    }
}

