package org.intuit.analysis.model;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;

/**
 * Represents a single sales record loaded from the CSV file.
 *
 * <p>This class models the structure of each row in the CSV, including:
 * sale ID, date, product details, pricing, quantity, region, and salesperson.</p>
 *
 * <p>It contains:
 * <ul>
 *     <li>A constructor to create an immutable Sale object</li>
 *     <li>A static {@code fromCsv} factory method to parse a CSV row</li>
 *     <li>Utility method {@code revenue()} to compute sale-level revenue</li>
 *     <li>Getter methods for all fields</li>
 * </ul>
 * </p>
 */
public class Sale {

    /**
     * Unique identifier for the sale
     */
    private final String saleId;

    /**
     * Date of the sale (parsed as LocalDate)
     */
    private final LocalDate date;

    /**
     * Identifier/code for the product
     */
    private final String productId;

    /**
     * Human-readable product name
     */
    private final String productName;

    /**
     * Product category
     */
    private final String category;

    /**
     * Unit price at which a single product was sold
     */
    private final double unitPrice;

    /**
     * Quantity of the product sold
     */
    private final int quantity;

    /**
     * Geographical region of the sale
     */
    private final String region;

    /**
     * Name of the salesperson responsible for the sale
     */
    private final String salesperson;

    /**
     * Creates a new immutable Sale object.
     *
     * @param saleId      Unique sale identifier
     * @param date        LocalDate representing the sale date
     * @param productId   Product ID
     * @param productName Product name
     * @param category    Product category
     * @param unitPrice   Price per unit
     * @param quantity    Units sold
     * @param region      Sales region
     * @param salesperson Salesperson name
     */
    public Sale(String saleId, LocalDate date, String productId, String productName,
                String category, double unitPrice, int quantity,
                String region, String salesperson) {

        this.saleId = saleId;
        this.date = date;
        this.productId = productId;
        this.productName = productName;
        this.category = category;
        this.unitPrice = unitPrice;
        this.quantity = quantity;
        this.region = region;
        this.salesperson = salesperson;
    }


    /**
     * Parses a single CSV line and converts it into a {@link Sale} object.
     *
     * <p>This method:
     * <ul>
     *     <li>Splits the CSV row by commas</li>
     *     <li>Trims whitespace around each value</li>
     *     <li>Parses the date into {@link LocalDate}</li>
     *     <li>Parses numeric fields such as unit price and quantity</li>
     * </ul>
     *
     * @param line A CSV line representing one sale (excluding header)
     * @return A fully populated Sale object
     */
    public static Sale fromCsv(String line) {

        // Split row by commas
        String[] parts = line.split(",");

        // Trim spaces from all columns to ensure clean parsing
        parts = Arrays.stream(parts)
                .map(String::trim)
                .toArray(String[]::new);

        // Date format pattern used in CSV
        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        // Construct a Sale object using parsed values
        return new Sale(
                parts[0],                               // saleId
                LocalDate.parse(parts[1], df),         // date
                parts[2],                               // productId
                parts[3],                               // productName
                parts[4],                               // category
                Double.parseDouble(parts[5]),           // unitPrice
                Integer.parseInt(parts[6]),             // quantity
                parts[7],                               // region
                parts[8]                                // salesperson
        );
    }

    /**
     * Calculates the revenue generated by this sale.
     * Revenue = unitPrice × quantity
     *
     * @return the total revenue for this sale
     */
    public double revenue() {
        return unitPrice * quantity;
    }

    public String getRegion() {
        return region;
    }

    public LocalDate getDate() {
        return date;
    }

    public String getProductId() {
        return productId;
    }

    public String getCategory() {
        return category;
    }

    public int getQuantity() {
        return quantity;
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    public String getSalesperson() {
        return salesperson;
    }
}
